TypeError: StableDiffusionProcessingTxt2ImgOv.__init__() missing 1 required positional argument: 'p'
TypeError: StableDiffusionProcessingTxt2ImgOv.__init__() missing 1 required positional argument: 'p'